# Generated by Django 2.1 on 2018-08-26 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('numberOfGames', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ESPNUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('name', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=25)),
                ('acronym', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekNum', models.IntegerField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='YahooUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='YahooUser',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='YahooUseType',
            fields=[
                ('pageName', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='yahoouse',
            name='useType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.YahooUseType'),
        ),
        migrations.AddField(
            model_name='yahoouse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.YahooUser'),
        ),
        migrations.AddField(
            model_name='game',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='wizard.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='roadTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadTeam', to='wizard.Team'),
        ),
        migrations.AddField(
            model_name='espnuse',
            name='useType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.YahooUseType'),
        ),
    ]
