# Generated by Django 2.1.1 on 2018-09-30 04:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeStamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeZone', models.CharField(default='US/Pacific', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageName', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.RemoveField(
            model_name='espnuse',
            name='useType',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='yahoouse',
            name='useType',
        ),
        migrations.DeleteModel(
            name='YahooUser',
        ),
        migrations.DeleteModel(
            name='ESPNUse',
        ),
        migrations.DeleteModel(
            name='YahooUse',
        ),
        migrations.DeleteModel(
            name='YahooUseType',
        ),
        migrations.AddField(
            model_name='use',
            name='useType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.UseType'),
        ),
    ]
