# Generated by Django 2.1 on 2018-08-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_auto_20180827_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='numberOfGames',
            field=models.IntegerField(default=0),
        ),
    ]
