# Generated by Django 2.1.1 on 2018-10-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_auto_20180929_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='use',
            name='leagueID',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='use',
            name='queryString',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
