# Generated by Django 2.1.1 on 2018-10-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0003_auto_20181003_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='leagueID',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
